- name: Install Middlewares
  tags: install
  hosts: all
  remote_user: pi
  sudo: yes
  tasks:
    - apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      with_items:
        - tree
    - synchronize: src=./package.json dest=~/sandbox/tact
